# Generated by Django 6.0.4 on 2026-04-29 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file_type', models.CharField(blank=True, max_length=10)),
                ('doc_type', models.CharField(choices=[('invoice', 'Invoice'), ('purchase_order', 'Purchase Order'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('supplier', models.CharField(blank=True, max_length=255)),
                ('document_number', models.CharField(blank=True, max_length=100)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, max_length=10)),
                ('subtotal', models.FloatField(blank=True, null=True)),
                ('tax', models.FloatField(blank=True, null=True)),
                ('total', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('review', 'Needs Review'), ('validated', 'Validated'), ('rejected', 'Rejected')], default='uploaded', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='LineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.FloatField()),
                ('unit_price', models.FloatField()),
                ('total', models.FloatField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='documents.document')),
            ],
        ),
        migrations.CreateModel(
            name='ValidationIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('severity', models.CharField(choices=[('error', 'Error'), ('warning', 'Warning')], default='error', max_length=10)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='documents.document')),
            ],
        ),
    ]
